"""Data models for the paper trading engine."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class CostBreakdown:
    """Itemized cost for a single trade."""
    spread_cost: float = 0.0
    slippage_cost: float = 0.0
    fx_cost: float = 0.0
    total_cost: float = 0.0
    gross_value: float = 0.0
    net_value: float = 0.0

    def to_dict(self) -> dict:
        return {
            "spread_cost": round(self.spread_cost, 4),
            "slippage_cost": round(self.slippage_cost, 4),
            "fx_cost": round(self.fx_cost, 4),
            "total_cost": round(self.total_cost, 4),
            "gross_value": round(self.gross_value, 4),
            "net_value": round(self.net_value, 4),
        }


@dataclass
class Trade:
    """A single executed trade event."""
    id: Optional[int] = None
    session_id: str = "default"
    position_id: Optional[int] = None
    symbol: str = ""
    action: str = ""  # buy / sell
    shares: float = 0.0
    price: float = 0.0
    costs: CostBreakdown = field(default_factory=CostBreakdown)
    timestamp: str = ""
    reason: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "session_id": self.session_id,
            "position_id": self.position_id,
            "symbol": self.symbol,
            "action": self.action,
            "shares": self.shares,
            "price": round(self.price, 4),
            "costs": self.costs.to_dict(),
            "timestamp": self.timestamp,
            "reason": self.reason,
        }


@dataclass
class Position:
    """An open or closed position."""
    id: Optional[int] = None
    session_id: str = "default"
    symbol: str = ""
    side: str = "long"
    shares: float = 0.0
    entry_price: float = 0.0
    entry_cost: float = 0.0
    exit_price: Optional[float] = None
    exit_proceeds: Optional[float] = None
    pnl: Optional[float] = None
    status: str = "open"
    entry_time: str = ""
    exit_time: Optional[str] = None
    entry_reason: str = ""
    exit_reason: str = ""

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "session_id": self.session_id,
            "symbol": self.symbol,
            "side": self.side,
            "shares": self.shares,
            "entry_price": round(self.entry_price, 4),
            "entry_cost": round(self.entry_cost, 4),
            "exit_price": round(self.exit_price, 4) if self.exit_price else None,
            "exit_proceeds": round(self.exit_proceeds, 4) if self.exit_proceeds else None,
            "pnl": round(self.pnl, 4) if self.pnl is not None else None,
            "status": self.status,
            "entry_time": self.entry_time,
            "exit_time": self.exit_time,
            "entry_reason": self.entry_reason,
            "exit_reason": self.exit_reason,
        }


@dataclass
class Signal:
    """A trading signal generated by rule evaluation."""
    symbol: str = ""
    action: str = "hold"  # buy / sell / hold
    strength: float = 0.0  # 0-1, how many rules matched
    reasons: list[str] = field(default_factory=list)
    indicators: dict = field(default_factory=dict)
    price: float = 0.0

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "action": self.action,
            "strength": round(self.strength, 4),
            "reasons": self.reasons,
            "indicators": {k: round(v, 4) if isinstance(v, float) else v
                          for k, v in self.indicators.items()},
            "price": round(self.price, 4),
        }


@dataclass
class DailySnapshot:
    """Daily portfolio state snapshot."""
    id: Optional[int] = None
    session_id: str = "default"
    date: str = ""
    cash: float = 0.0
    positions_value: float = 0.0
    total_value: float = 0.0
    daily_pnl_gross: float = 0.0
    daily_pnl_net: float = 0.0
    cumulative_pnl_gross: float = 0.0
    cumulative_pnl_net: float = 0.0
    total_spread_cost: float = 0.0
    total_slippage_cost: float = 0.0
    total_fx_cost: float = 0.0
    estimated_tax: float = 0.0
    daily_pnl_after_tax: float = 0.0
    cost_drag_pct: float = 0.0
    trades_today: int = 0
    wins_today: int = 0
    losses_today: int = 0

    def to_dict(self) -> dict:
        return {
            "date": self.date,
            "cash": round(self.cash, 2),
            "positions_value": round(self.positions_value, 2),
            "total_value": round(self.total_value, 2),
            "daily_pnl_gross": round(self.daily_pnl_gross, 2),
            "daily_pnl_net": round(self.daily_pnl_net, 2),
            "cumulative_pnl_gross": round(self.cumulative_pnl_gross, 2),
            "cumulative_pnl_net": round(self.cumulative_pnl_net, 2),
            "total_spread_cost": round(self.total_spread_cost, 2),
            "total_slippage_cost": round(self.total_slippage_cost, 2),
            "total_fx_cost": round(self.total_fx_cost, 2),
            "estimated_tax": round(self.estimated_tax, 2),
            "daily_pnl_after_tax": round(self.daily_pnl_after_tax, 2),
            "cost_drag_pct": round(self.cost_drag_pct, 2),
            "trades_today": self.trades_today,
            "wins_today": self.wins_today,
            "losses_today": self.losses_today,
        }


@dataclass
class PortfolioSummary:
    """Current portfolio state."""
    session_id: str = "default"
    broker_profile: str = "etoro"
    initial_capital: float = 0.0
    cash: float = 0.0
    positions: list[dict] = field(default_factory=list)
    positions_value: float = 0.0
    total_value: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    total_costs: float = 0.0
    cost_breakdown: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "session_id": self.session_id,
            "broker_profile": self.broker_profile,
            "initial_capital": round(self.initial_capital, 2),
            "cash": round(self.cash, 2),
            "positions": self.positions,
            "positions_value": round(self.positions_value, 2),
            "total_value": round(self.total_value, 2),
            "unrealized_pnl": round(self.unrealized_pnl, 2),
            "realized_pnl": round(self.realized_pnl, 2),
            "total_costs": round(self.total_costs, 2),
            "cost_breakdown": self.cost_breakdown,
        }
